x-dns: &dns
  dns: ${NETWORK}.0.254

services:
  dns:
    container_name: dns
    build:
      context: ./docker/dns
      args:
        NETWORK: ${NETWORK}
    networks:
      localnet:
        ipv4_address: ${NETWORK}.0.254
        
  a-client:
    <<: *dns
    container_name: a-client
    build:
      context: ./docker/client
    networks:
      localnet:
        ipv4_address: ${NETWORK}.1.1

  a-imap:
    <<: *dns
    container_name: a-imap
    build:
      context: ./docker/imap
      args:
        HOSTNAME: imap.a.test
    networks:
      localnet:
        ipv4_address: ${NETWORK}.1.10

  a-smtp-plain:
    <<: *dns
    container_name: a-smtp-plain
    build:
      context: ./docker/smtp-plain
      args:
        HOSTNAME: plain.smtp.a.test
    networks:
      localnet:
        ipv4_address: ${NETWORK}.1.30

  a-smtp-dkim:
    <<: *dns
    container_name: a-smtp-dkim
    build:
      context: ./docker/smtp-rspamd
      args:
        HOSTNAME: dkim.smtp.a.test
        NETWORK: ${NETWORK}
    networks:
      localnet:
        ipv4_address: ${NETWORK}.1.31

  b-imap:
    <<: *dns
    container_name: b-imap
    build:
      context: ./docker/imap
      args:
        HOSTNAME: imap.b.test
        DOMAIN: b.test
    networks:
      localnet:
        ipv4_address: ${NETWORK}.2.10

  b-mx:
    <<: *dns
    container_name: b-mx
    build:
      context: ./docker/mx-plain
      args:
        HOSTNAME:  plain.mx.b.test
        RELAYHOST: imap.b.test
    networks:
      localnet:
        ipv4_address: ${NETWORK}.2.20

  b-mx-spf:
    <<: *dns
    container_name: b-mx-spf
    build:
      context: ./docker/mx-rspamd
      dockerfile: Dockerfile
      args:
        HOSTNAME:  spf.mx.b.test
        RELAYHOST: imap.b.test
        ROLE: spf
    networks:
      localnet:
        ipv4_address: ${NETWORK}.2.21

  b-mx-dkim:
    <<: *dns
    container_name: b-mx-dkim
    build:
      context: ./docker/mx-rspamd
      dockerfile: Dockerfile
      args:
        HOSTNAME:  dkim.mx.b.test
        RELAYHOST: imap.b.test
        ROLE: dkim
    networks:
      localnet:
        ipv4_address: ${NETWORK}.2.22

  b-mx-dmarc:
    <<: *dns
    container_name: b-mx-dmarc
    build:
      context: ./docker/mx-rspamd
      dockerfile: Dockerfile
      args:
        HOSTNAME:  dmarc.mx.b.test
        RELAYHOST: imap.b.test
        ROLE: dmarc
    networks:
      localnet:
        ipv4_address: ${NETWORK}.2.23

networks:
  localnet:
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${NETWORK}.0.0/16
