x-dns: &dns
  dns: ${NETWORK}.0.254

services:
  b-imap:
    build:
      args:
        HOSTNAME: imap.b.test
        DOMAIN: b.test
        FORWARD_TO: c.test

  c-imap:
    <<: *dns
    container_name: c-imap
    build:
      context: ./docker/imap
      args:
        HOSTNAME: imap.c.test
        DOMAIN: c.test
    networks:
      localnet:
        ipv4_address: ${NETWORK}.3.10

  c-mx:
    <<: *dns
    container_name: c-mx
    build:
      context: ./docker/mx-plain
      args:
        HOSTNAME:  plain.mx.c.test
        RELAYHOST: imap.c.test
    networks:
      localnet:
        ipv4_address: ${NETWORK}.3.20
