services:
  base:
    build:
      context: .
      dockerfile: Dockerfile-base
    image: smtp-book-base:latest

  postfix:
    build:
      context: .
      dockerfile: Dockerfile-postfix
    depends_on: 
      - base
    image: smtp-book-postfix:latest

  dovecot:
    build:
      context: .
      dockerfile: Dockerfile-dovecot
    depends_on: 
      - postfix
    image: smtp-book-dovecot:latest

  unbound:
    build:
      context: .
      dockerfile: Dockerfile-unbound
    depends_on: 
      - base
    image: smtp-book-unbound:latest

  smtp-dkim:
    build:
      context: .
      dockerfile: Dockerfile-smtp-dkim
    depends_on: 
      - postfix
    image: smtp-book-smtp-dkim:latest

  mx-spf:
    build:
      context: .
      dockerfile: Dockerfile-mx-spf
    depends_on: 
      - postfix
    image: smtp-book-mx-spf:latest

  mx-spf-dkim:
    build:
      context: .
      dockerfile: Dockerfile-mx-spf-dkim
    depends_on: 
      - mx-spf
    image: smtp-book-mx-spf-dkim:latest