FROM smtp-book-postfix:latest

RUN export DEBIAN_FRONTEND="noninteractive" && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
    dovecot-core dovecot-imapd && \
    rm -rf /var/lib/apt/lists/*
