services:
  dns:
    container_name: dns
    build:
      context: ./dns
    networks:
      localnet:
        ipv4_address: 10.100.2.254

  a-client:
    container_name: a-client
    dns: 10.100.2.254
    build:
      context: ./a-client
    networks:
      localnet:
        ipv4_address: 10.100.2.5
  
  a-smtp-plain:
    container_name: a-smtp-plain
    dns: 10.100.2.254
    build:
      context: ./a-smtp-plain
    networks:
      localnet:
        ipv4_address: 10.100.2.50
    ports:
      - "0.0.0.0:10025:25"

  a-smtp-dkim:
    container_name: a-smtp-dkim
    dns: 10.100.2.254
    build:
      context: ./a-smtp-dkim
    networks:
      localnet:
        ipv4_address: 10.100.2.60
    ports:
      - "0.0.0.0:11025:25"

  b-mx:
    container_name: b-mx
    dns: 10.100.2.254
    build:
      context: ./b-mx
    networks:
      localnet:
        ipv4_address: 10.100.2.70

  b-mx-spf:
    container_name: b-mx-spf
    dns: 10.100.2.254
    build:
      context: ./b-mx-spf
    networks:
      localnet:
        ipv4_address: 10.100.2.71

  b-mx-spf-dkim:
    container_name: b-mx-spf-dkim
    dns: 10.100.2.254
    build:
      context: ./b-mx-spf-dkim
    networks:
      localnet:
        ipv4_address: 10.100.2.72

  b-imap:
    container_name: b-imap
    dns: 10.100.2.254  
    build:
      context: ./b-imap
    networks:
      localnet:
        ipv4_address: 10.100.2.20  
    ports:
      - "0.0.0.0:20143:143"


networks:
  localnet:
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.100.2.0/24
