FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    unbound \
    dnsutils \
    iputils-ping \
    vim \
    iproute2 \
    && rm -rf /var/lib/apt/lists/*

COPY config/unbound/unbound.conf /etc/unbound/unbound.conf
EXPOSE 53/TCP 53/UDP

ENTRYPOINT ["unbound-control","start"]