FROM kasuyamofu/smtpbook-base:latest

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    unbound && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/unbound/var/log          && \
    touch /etc/unbound/var/log/unbound.log && \
    rm /etc/unbound/unbound.conf.d/*

COPY unbound/unbound.conf /etc/unbound/unbound.conf
COPY unbound/unbound.conf.d/* /etc/unbound/unbound.conf.d/

RUN chown -R unbound:unbound /etc/unbound